SELECT TOP (1000) [VendorID]
      ,[VendorName]
      ,[VendorAddress1]
      ,[VendorAddress2]
      ,[VendorCity]
      ,[VendorState]
      ,[VendorZipCode]
      ,[VendorContactLName]
      ,[VendorContactFName]
      ,[VendorPhone]
      ,[TermsID]
      ,[AccountNo]
      ,[LastTranDate]
      ,[YTDPurchases]
      ,[YTDReturns]
      ,[LastYTDPurchases]
      ,[LastYTDReturns]
  FROM [Examples].[dbo].[Vendors]